### ISSUE TITLE
Intended use of at_home

### ISSUE THREAD

**Issue by bryanhanson** [markvanderloo/tinytest#10]
I really like this option to have some tests run `at_home`, but I'm a little unclear on how it is intended to be used.  Let's say I put a file `test_something` with a test in it into the `inst/tinytest` folder.  In `test_something` I put code like this:

```
if ( at_home() ) {... do a test ...}
```

Then, in `R` I do `Sys.setenv(TT_AT_HOME = "TRUE")` and tests wrapped as above will be run during local checking (and not for instance at CRAN since they won't have set the environmental variable).  Is that the intended approach?  The vignette seems to suggest there is another way that doesn't involve the environmental variable but I don't quite get what the vignette is trying to say.  Thanks.

**Comment by markvanderloo** [comment]
Good question and I will document this more clearly in the next update. Here's the idea.

You use the following in the script.
```r
if (at_home()){
   # some tests
}
```
When you use `test_all()`, `build_install_test()`, `test_dir` or `test_file`, the `#some tests` will run. you can turn them off as follows: `test_dir(..., at_home=FALSE)`.

By default, the `at_home()` tests are NOT run from R CMD check. The default `at_home` value for
`test_package` is `FALSE`. So here is what you do in `tinytest.R`

```r
if (requireNamespace("tinytest", quietly=TRUE)){
   home <- identical(Sys.getenv("HONEYIMHOME"), "TRUE")
   tinytest::test_package("packagename", at_home=home)
}
```
now, here I use an env var (to be set in your OS), but you can also detect your computer's name or your user name to tell `test_package` that you are at home. @eddelbuettel reads the DESCRIPTION file and detects if the version number has 4 digits (he always pushes to CRAN with 3 digits and uses 4 digits for build versioning).


Hope that clears it up a little, if not: ask me!

**Comment by eddelbuettel** [comment]
I have been using `tinytest` for two weeks and clearly did not understand this either.  To me it was always easiest to ... just cook something up myself.  

Which we did eg for Rcpp with the a.b.c (few test) versus dev version a.b.c.d (all tests) here (still using RUnit):  
https://github.com/RcppCore/Rcpp/blob/6062d561939e72a9a6bbf0d0b3a2311374be3552/tests/doRUnit.R#L46-L53
I told Hadley about that at length years ago too but of course testthat did something different. Anyway.

I find the name `at_home` a little suboptimal. Maybe we should settle on something more describe _with respect to the test scope intent_ and then define a rule (or a set of rules) to tickle it. Including env vars.  What @markvanderloo has right now may be not quite transparent enough of he needs three paragraphs to explain it :)

**Comment by bryanhanson** [comment]
Thank you Mark, I think I know how to proceed.

My desire is a simple set up.  I want all tests in a single directory, the one required by `test_package`.  Within the individual `test_` scripts I can check to see if `at_home` is `TRUE` by any of the means you suggest, and tests are run accordingly.  So when doing `R CMD CHECK` `test_package` is always called, but then some tests are skipped if on CRAN.

From the developer's point of view this is simple.  I don't know all possible use cases that might be desirable.  However, someone else testing my package or contributing to the package would probably need a way to override my definition of `at_home`, but this is possible with `test_all`. Or I guess some environment variable could be created when the package is attached and this is what drives `at_home` so that it works for anyone.

**Comment by eddelbuettel** [comment]
And I think in some other packages I even tested for user name and hostname to turn tests on/off because the package actually needed resources (such as eg a running database backend, or remote api with user/id in another authentication thread).  So programmatically deciding is always an option, but an easier/nicer default would be nice too.

**Comment by markvanderloo** [comment]
I have completely rewritten this in the vignette  (Section 4) and also in the manual. I think the current functionality is now sufficiently clear and we can use it as a reference. In short:

- `R CMD check` by default runs as if on CRAN, but you can program something smarter around it easily.
- `test_all` and friends by default runs as if not on CRAN, but this can be controlled.

So I will close this for now, maybe we can come up with something better, but I feel that's for another issue

ref: https://github.com/markvanderloo/tinytest/commit/e5bfcd433666a656cacc885576de9788ddfb702b

**Comment by vinhdizzo** [comment]
Hey @markvanderloo , I came across this post as I was confused on how to skip tests using the `at_home`  argument as described in section 4 of the "Using tinytest" vignette (tinytest version 1.3.1).

It's more clear to me now after seeing [this](https://github.com/markvanderloo/tinytest/issues/10#issuecomment-499848278) comment.  I think it would be more clear to users if you explicitly state in the vignette: Users can skip tests (not at home) by wrapping skipped tests in their `./inst/tinytest/*.R` scripts with the following:

```r
if (at_home()){
   # some tests
}
```

I think this last piece is missing in the vignette.  Just my 2 cents.  Please let me know if I've misinterpreted.
