### ISSUE TITLE
Feature suggestion: `skip_on_cran()` and `skip_on_ci()` flags 

### ISSUE THREAD

**Issue by s3alfisc** [markvanderloo/tinytest#105]
Hi Mark, 

Have you considered to add functionality equivalent to `testthat::skip_on_cran()` and `testthat::skip_on_ci()`? I believe that both could be greatly appreciated by many users. My own story with `tinytest` is that - even though I very much enjoyed using the package - I at some point switched to `testthat`, because I could not figure out how to skip tests on CI (i.e. github actions), and skipping tests on CRAN by package versioning at some point felt too cumbersome in contrast to simply putting a `skip_on_cran()` flag on top of my testing script. 

Best, Alex

**Comment by markvanderloo** [comment]
It is impossible to detect with certainty whether you are running on CRAN, as the CRAN team does not release any information that identifies their system. In `tinytest` you can do
```r
if (at_home()){
 # some naughty tests that are not allowed on CRAN.
}
```

**Comment by markvanderloo** [comment]
The basic mechanism you can use (and this is also what `at_home()` uses) is to set an env var _on your own system_. That way you can always detect whether you are at home, or somewhere else.

@eddelbuettel uses another mechanism: he uses a 4-digit version number for build issues, and 3 digits on release. using `read.dcf` you can detect whether your at home building things or if you're testing a release version (which is also what ends up on CRAN).

So the test is not whether you are at someone else's system. The test is if you are at a system you control.

**Comment by eddelbuettel** [comment]
I agree. To me, the `NOT_CRAN` mechanism is fundamentally broken.

@s3alfisc: I encourage you to be more creative with this. A truly great beauty of `tinytest` is that _all_ its test files are just scripts and I have ("literally" as the kids says) a bazillion of `exit_file()` statements across my various packages using.  *You* are in control of where *you* want to quit or skip. Could not be better.

```sh
$ grep exit_file git/rcpp/inst/tinytest/*R | wc -l
59
$
```

**Comment by s3alfisc** [comment]
Hi @markvanderloo and @eddelbuettel - thanks for both of your feedback on this! I very much agree with @eddelbuettel that I should become more creative here. Unfortunately, sometimes I am just lazy (in particular when writing unit tests at the end of a workday) =) To help out "lazy" developers, maybe it could make sense to add a small section to the vignette that sketches different approaches to solve the task at hand? I could offer to draft a brief section within the next two weeks or so, if you would be interested in that, Mark? I am also tagging Dirk's [stackoverflow answer](https://stackoverflow.com/questions/36166288/skip-tests-on-cran-but-run-locally) from a few years ago, which might help other `tinytest` users who stumble over this thread when searching for strategies to skip tests on CRAN/CI.

**Comment by eddelbuettel** [comment]
People in my age bracket know lazyness is a virtue (as Larry Wall extolled in the O'Reilly `perl` books we all consumed before kids now in undergrad were even born).  So package `Rcpp`, and even I sometimes forget that, only run (most of its) tests if an opt-in environment variable is set (to keep it shorter at CRAN).  (What @markvanderloo mentioned about the version number scheme is another layer that may automagically set the environment variable in package code.)  In other packages needing external (REST) APIs I similarly only test if a conditioning variable is set.  So back to what I suggested: your desire, your scope, your ability to set it up _exactly_ as you like it.  If none of that pleases you well there the market-leading flavour with its (to me: blunter) approach.  You have choices, and well like that.

I think this can be closed.
