### ISSUE TITLE
Warning following test_package()

### ISSUE THREAD

**Issue by zpneal** [markvanderloo/tinytest#107]
I've switched the `backbone` package from `testthat` to `tinytest`. Everything seems to be working, except when I run `tinytest::test_package("backbone")` I get:

```
Warning message:
In structure(unlist(test_output, recursive = FALSE), class = "tinytests",  :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

**Comment by markvanderloo** [comment]
Hi there, I pulled the `devel` branch of your package, and if I start R in the `backbone` directory and run

```r
library(tinytest)
build_install_test()
```
everything runs fine. Next I run

```bash
R CMD INSTALL ./
R -e 'tinytest::test_package("backbone")'
```
in the command line all runs fine as well.

**Comment by zpneal** [comment]
Thanks. Strangely, I'm no longer able to replicate the error. Seems to be working fine for me too now. Thanks for a really helpful tiny package.
