### ISSUE TITLE
Optionally have `expect_condition()` fail if unexpected conditions also occur

### ISSUE THREAD

**Issue by joshuaulrich** [markvanderloo/tinytest#108]
This is a feature request, not a bug.

I had an `expect_warning()` test pass because it threw the expected warning, but the tested expression also threw an error because of a bug. Thankfully, I happened to notice the bug because I was migrating to tinytest from RUnit. But I wouldn't have noticed it if I only wrote the test with tinytest.

Here's an example:

```
R$ # I get the warning I expected, but an unexpected error also happened
R$ tinytest::expect_warning({ warning("warn"); stop("error") })
----- PASSED      : <-->
 call| tinytest::expect_warning({
 call| warning("warn")
 call| stop("error")
 call| })
```

It would be great if there were an option to be more strict about the expectations for conditions. I would want options to make sure:
1. Only the expected condition is thrown, and/or
2. No conditions worse than the expected condition are thrown:
    * `expect_message()` fails if a warning or error also occurs
    * `expect_warning()` fails if an error is thrown later

I understand that making either of these the default behavior could break other packages' tests. That said, the current behavior can potentially hide bugs. So perhaps the default behavior for `expect_condition()` functions could add a NOTE/WARNING to the printed output (for case 1 and/or 2), and maybe even throw warning in case 2.

**Comment by markvanderloo** [comment]
Good point. I think I'll add something like a `strict` parameter that is set to the current behavior by default.

**Comment by markvanderloo** [comment]
Current status (gotta fix that NA, but otherwise seems fine)

```r
> expect_warning({warning("foo!"); stop("bar!"); message("buzz!")},strict=TRUE)
----- FAILED[]: <-->
 call| expect_warning({
 call| warning("foo!")
 call| stop("bar!")
 call| message("buzz!")
 call| }, strict = TRUE)
 diff| NA
 diff| Found 1 warning(s) and 1 error(s):
 diff| WRN: foo! 
 diff| ERR: bar! 
> expect_warning({warning("foo!"); stop("bar!"); message("buzz!")},strict=FALSE)
----- PASSED      : <-->
 call| expect_warning({
 call| warning("foo!")
 call| stop("bar!")
 call| message("buzz!")
 call| }, strict = FALSE) 


```

**Comment by markvanderloo** [comment]
Done. See also [pkg/inst/tinytest/test_gh_issue_108.R](https://github.com/markvanderloo/tinytest/blob/master/pkg/inst/tinytest/test_gh_issue_108.R)

```r
> expect_warning({message("buzz!"); warning("foo!"); stop("bar!")},strict=TRUE)
----- FAILED[]: <-->
 call| expect_warning({
 call| message("buzz!")
 call| warning("foo!")
 call| stop("bar!")
 call| }, strict = TRUE)
 diff| NA
 diff| Found 1 message(s), 1 warning(s), and 1 error(s):
 diff| MSG: buzz!
 diff| WRN: foo! 
 diff| ERR: bar! 
> 
> 
> expect_warning({message("buzz!"); warning("foo!"); stop("bar!")},strict=FALSE)
----- PASSED      : <-->
 call| expect_warning({
 call| message("buzz!")
 call| warning("foo!")
 call| stop("bar!")
 call| }, strict = FALSE) 

```
