### ISSUE TITLE
Support for exception tests with a 'tinytest::' prefix.

### ISSUE THREAD

**Issue by ltuijnder** [markvanderloo/tinytest#113]
Hi. I encountered the following when embarking on my tinytest journey.

Say I wrote a very simple tests file: `test_file.R`
```
add_one <- function(x) x + 1
tinytest::expect_equal(add_one(1), 2)
tinytest::expect_equal(add_one(2), 2)
```
And I run the test file: `tinytest::run_test_file("test_file.R")` 

I get the following message back in my console:
```
 You are using 'tinytest::' to express test expectations.
 The results from these tests are not collected. Found the following occurrences:
 > test_file.R#002: tinytest::expect_equal
 > test_file.R#003: tinytest::expect_equal 
 Remove the 'tinytest::' prefix to register the test results.FALSE
```

My question why this behaviour? Are there technical limitations to why exceptions prefixed with `tinytest::` cannot be collected? Nor do I see why prefixing the package name would go against the philosophy.  

I looked through tinytest documentation and searched online, but I could not find an answer to why test exceptions should not have a package namespace prefix.

Personally, I like to prefix package names as my IDE then immediately helps me out with all the available expect options. In general, I think it is good behaviour to prefix package names when writing R packages so I applied my instinct also to writing tests.  

I would like to hear your thoughts on why this behaviour. And ideally, if it could also be supported to write test with `tinytest::` prefixes.

**Comment by markvanderloo** [comment]
Hi there,

there is indeed a [technical reason](https://journal.r-project.org/archive/2021/RJ-2021-056/RJ-2021-056.pdf). It has to do with the mechanism used to capture the output of the `expect_` functions.

I should probably explicitly document that the `tinytest::` can not be used.

**Comment by ltuijnder** [comment]
Hi @markvanderloo 

So I read through your paper, and I have to say it was a pleasant read. It explains so many things! 

* I was confused by the internals of the expect_* function on how they communicate information without conditions
* I was confused why I could not use `tinytest::`
* I was confused why I did not need to call library("tinytest") the expect_* functions where some how still available.

It is all explained by the function masking and the local-side effects. Awesome! Really cool that you shared this info and insight on how tinytest works.

I think it would be useful to have the paper also be somewhere linked in the documentation. For example in the README and/or in a Reference section in the documentation or a small dedicated section in the vignette.

For example, the user facing `tinytest::report_side_effects` is SUPER simplistic. But that is because all the complexity is hidden inside the run functions. The documentation of this function does not give any hints HOW the side effects are getting recorded. I think just a simple reference to the technical paper could really help a lot with transparency of the code.

In either case thanks for sharing the knowledge. :)

**Comment by ltuijnder** [comment]
Closing this issue as it is explained with the technical reasons on why one could not use the `tinytest::` prefix.

**Comment by markvanderloo** [comment]
Thanks for the compliments! I could indeed add some references to this paper. The techniques described there have been useful in several places (for me at least).
