### ISSUE TITLE
`exit_if_not` always exits?

### ISSUE THREAD

**Issue by vincentarelbundock** [markvanderloo/tinytest#116]
It's a bit late for me, but is there any chance this commit broke `exit_if_not`? https://github.com/markvanderloo/tinytest/commit/88750e92eae85309451fd989e077d8b95517e81a

Setup package with a working test

```sh
Rscript -e "pkgKitten::kitten('bugreport')"
Rscript -e "tinytest::puppy('bugreport')"
cd bugreport
echo "expect_true(pi > 3)\n" > inst/tinytest/test-runs.R
```

`exit_if_not` exits correctly and reports the exit:

```sh
echo "exit_if_not(2 < 1) \n expect_true(pi > 3)\n" > inst/tinytest/test-exits.R
Rscript -e "tinytest::build_install_test();packageVersion('tinytest')"
```

```r
test_bugreport.R..............    1 tests OK 33ms
test-exits.R..................    0 tests    1ms [Exited at #2: '2 < 1' is not TRUE]
test-runs.R...................    1 tests OK 1ms
All ok, 2 results (38ms)
[1] ‘1.4.1’
```

`exit_if_not` exits *in*correctly and does *not* report the exit:

```sh
rm inst/tinytest/test-exits.R
echo "exit_if_not(2 > 1) \n expect_true(pi > 3)\n" > inst/tinytest/test-exits.R
Rscript -e "tinytest::build_install_test();packageVersion('tinytest')"
```

```r
test_bugreport.R..............    1 tests OK 33ms
test-runs.R...................    1 tests OK 1ms
All ok, 2 results (41ms)
[1] ‘1.4.1’
``

**Comment by markvanderloo** [comment]
Will have a look. Chasing a bug in 'validate' now :-).

**Comment by markvanderloo** [comment]
Just checked: seems that exit_if_not does the exact opposite of what is
should do :D.

Its new in this release so it should not bother anyone. Will fix and upload
a new version soon. (latest release with the newest bugs!)

-Mark

**Comment by vincentarelbundock** [comment]
Cool, thanks.

The thing that tripped me up is that I couldn't just reverse an exit condition with `!`. In my second example above, the `test-exits.R` file appears to be skipped either way, and in one case the exit is not reported at all.

I replicated that in a bigger package too, and tests are skipped whether the exit condition is `TRUE` or `FALSE`.

**Comment by markvanderloo** [comment]
If I stick this in a file x.R

exit_if_not(1==3)

expect_equal(1,1)


and then run
***@***.***:~/projects/tinytest$ R -s -e 'tinytest::run_test_file("x.R");
packageVersion("tinytest")'
x.R...........................    0 tests    43ms [Exited at #4: '1 == 3'
is not TRUE]
All ok, 0 results (43ms)
[1] '1.4.1'


all is fine.

**Comment by markvanderloo** [comment]
Ok, now I set up the package with your script, and I get this (see below).
All seems fine.

Also, I double-checked but exit_if_not() is part of the unit testing suite
in tinytest, so a change in behavior I should have noticed.

This is weird.
-Mark


***@***.***:~/projects/tmp/bugreport$ R -s -e
'tinytest::build_install_test();packageVersion("tinytest")'
* checking for file ‘/home/mark/projects/tmp/bugreport/DESCRIPTION’ ... OK
* preparing ‘bugreport’:
* checking DESCRIPTION meta-information ... OK
* installing the package to process help pages
* saving partial Rd database
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘bugreport_1.0.tar.gz’

* installing *source* package ‘bugreport’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation
path
* DONE (bugreport)
test_bugreport.R..............    1 tests OK 37ms
test-exits.R..................    0 tests    1ms [Exited at #3: '2 < 1' is
not TRUE]
test-runs.R...................    1 tests OK 1ms
All ok, 2 results (42ms)
[1] ‘1.4.1’

**Comment by vincentarelbundock** [comment]
That's super weird. I uninstalled `tinytest` and reinstalled from CRAN source and am still getting the problem. Not sure what to say...

```r
> library(tinytest)
> list.files("inst/tinytest/")
[1] "test_bugreport.R" "test-exits.R"     "test-runs.R"     
> readLines("inst/tinytest/test-exits.R")
[1] "exit_if_not(2 > 1) "  " expect_true(pi > 3)" ""                    
> run_test_dir("inst/tinytest/")
test_bugreport.R..............    1 tests OK 88ms
test-runs.R...................    1 tests OK 43ms
All ok, 2 results (0.2s)
> sessionInfo()
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] tinytest_1.4.1

loaded via a namespace (and not attached):
[1] compiler_4.2.2 parallel_4.2.2 bspm_0.3.9    
```

**Comment by vincentarelbundock** [comment]
Seems to work on my machine too. Thanks!
