### ISSUE TITLE
[Feature Request] terminal awareness

### ISSUE THREAD

**Issue by eddelbuettel** [markvanderloo/tinytest#12]
Being a YUGE fan of `tinytest` I now use it all the time at the command-line, which of course lead 
to (starting to write an approximation to a) first [command-line wrapper using littler](https://github.com/eddelbuettel/littler/commit/e706917c46f6052b6305a59d55a16b940f1f3a8b).

One nicety with having these shorter wrapper is that one can then use `C-x c` to invoke the `compile-command` which is an editable string we can replace from its default of `make -k` to, say, `tt.r -a` to invoke the `tinytest` wrapper in `test_all()` mode on the current directory. 

Which works swimmingly but renders a somewhat unreadable display:

```
-*- mode: compilation; default-directory: "~/git/anytime/" -*-
Compilation started at Sat Jun  8 09:56:43

tt.r -a
Running test_all_formats.R (00|[0;32m00[0m|[0;31m00[0m)
Running test_all_formats.R (36|[0;32m36[0m|[0;31m00[0m)
Running test_assertions.R (02|[0;32m02[0m|[0;31m00[0m)
Running test_bulk.R (2328|[0;32m2328[0m|[0;31m00[0m)
Running test_gh_issue_12.R (02|[0;32m02[0m|[0;31m00[0m)
Running test_gh_issue_33.R (02|[0;32m02[0m|[0;31m00[0m)
Running test_gh_issue_5.R (04|[0;32m04[0m|[0;31m00[0m)
Running test_gh_issue_56.R (07|[0;32m07[0m|[0;31m00[0m)
Running test_gh_issue_84.R (00|[0;32m00[0m|[0;31m00[0m)
Running test_gh_issues_36_51.R (00|[0;32m00[0m|[0;31m00[0m)
Running test_r_format.R (01|[0;32m01[0m|[0;31m00[0m)
Running test_simple.R (25|[0;32m25[0m|[0;31m00[0m)
Running test_utilities.R (03|[0;32m03[0m|[0;31m00[0m)
Running test_validate.R (07|[0;32m07[0m|[0;31m00[0m)

Compilation finished at Sat Jun  8 09:56:44
```

So could we, in a dumb terminal, turn of the otherwise excellent colours?

**Comment by eddelbuettel** [comment]
BTW the `TERM` variable is (literally) set to `dumb` :

```
-*- mode: compilation; default-directory: "~/git/anytime/" -*-
Compilation started at Sat Jun  8 10:02:11

echo $TERM
dumb

Compilation finished at Sat Jun  8 10:02:11
```

**Comment by eddelbuettel** [comment]
We can close this, or leave it open anyway for others to gaze at ... but I already had a snippet in `~/.Rprofile` that loops over a directory `~/.Rprofile.d/` of snippets so I just added

```r
if (Sys.getenv("TERM") == "dumb") {
    #cat("In dumb terminal\n")
    options("tt.pr.color"=FALSE)
}
```

and now I get 

```
-*- mode: compilation; default-directory: "~/git/anytime/" -*-
Compilation started at Sat Jun  8 10:37:48

tt.r -a
Running test_all_formats.R (T00|P00|F00)
Running test_all_formats.R (T36|P36|F00)
Running test_assertions.R (T02|P02|F00)
Running test_bulk.R (T2328|P2328|F00)
Running test_gh_issue_12.R (T02|P02|F00)
Running test_gh_issue_33.R (T02|P02|F00)
Running test_gh_issue_5.R (T04|P04|F00)
Running test_gh_issue_56.R (T07|P07|F00)
Running test_gh_issue_84.R (T00|P00|F00)
Running test_gh_issues_36_51.R (T00|P00|F00)
Running test_r_format.R (T01|P01|F00)
Running test_simple.R (T25|P25|F00)
Running test_utilities.R (T03|P03|F00)
Running test_validate.R (T07|P07|F00)

Compilation finished at Sat Jun  8 10:37:49
```

which is more readable.

**Comment by markvanderloo** [comment]
Thanks for this thread. For other ppl reading this: all interactive test runners, like `run_test_dir` or `test_all` accept an argument `color`, of which the default value is `TRUE`. You can set a global option like Dirk does or pass `color=FALSE` to ignore colors for a single run.

**Comment by eddelbuettel** [comment]
One thought:  You could also at package load see if the terminal is `dump` and then adjust your global setting.

**Comment by markvanderloo** [comment]
That's actually a great idea.

**Comment by eddelbuettel** [comment]
Nice. Sitting at airport on laptop where I had not taught `tinytest` to turn colours off.

**Comment by markvanderloo** [comment]
Ok, so after a bit of googling. Being sure whether a terminal supports ANSI escape codes is not all that trivial. [Here's a `js` library](https://github.com/keqingrong/supports-ansi/blob/master/index.js) that does it, and basically it has a lot of OS-dependent knowledge in there.

So `Sys.getenv("TERM")=="dumb"` will not catch all but it _does_ guarantee the lack of ANSI support so I'll to that for now, but we keep in mind that there may be other cases not caught automatically.

**Comment by markvanderloo** [comment]
Resolved in https://github.com/markvanderloo/tinytest/commit/032eb160b60c0e5982a6524407831e07d09f04ce
