### ISSUE TITLE
What do you think about expect_silent? (opinion, maybe feature request)

### ISSUE THREAD

**Issue by bryanhanson** [markvanderloo/tinytest#14]
I have a optimization function that I'd like to test, in the sense that it runs without error or warning -- not to check the output values per se.  It can have lots of graphical output. Currently it is an example wrapped in `\dontrun{}` so it is not tested, and it takes about 90 seconds and so it would be ideal for an `at_home` situation.

If I were using `testthat` I would use `expect_silent`  But of course (strongly) want to use `tinytest`!  Have you considered something equivalent to `expect_silent`?  I can't make  up my mind if testing for silence is worthwhile as an option or even theoretically -- I do think it's consistent however with your "test the surface" recommendation, which I really like.  It's a user-facing function and I need to know if any of its moving parts have broken.

So, I'm seeking your opinion about the value of `expect_silent` and how to handle this situation.  As this is a possibly open-ended question I will not be upset if you close it.

**Comment by markvanderloo** [comment]
I think it's a good idea. In these cases I usually did something like `capture.output(expression)`, but it is better to have a formal expectation for it. It's on the list :-).

**Comment by markvanderloo** [comment]
Ok, almost weekend and added it:

```r
> library(tinytest)
> packageVersion("tinytest")
[1] ‘0.9.4.4’
> expect_silent(1+1)
----- PASSED      : <-->
 call| expect_silent(1 + 1) 
> expect_silent(1+"a")
----- FAILED[xcpt]: <-->
 call| expect_silent(1 + "a")
 diff| Execution was not silent. An Error was thrown with message
 diff| 'non-numeric argument to binary operator' 
> expect_silent(1:3+1:2)
----- FAILED[xcpt]: <-->
 call| expect_silent(1:3 + 1:2)
 diff| Execution was not silent. A Warning was thrown with message
 diff| 'longer object length is not a multiple of shorter object length' 
```

Please give it a whirl and close if ok.

**Comment by markvanderloo** [comment]
I think that `expect_silent` will be useful for testing `print` methods. Not to compare the output with some string but just to make sure noting crashes if some underlying code is changed. For this reason I now make `expect_silent` dump output printed by the tested expression to `dev/null`.

```r
> library(tinytest)
> expect_silent(print("hihi"))
----- PASSED      : <-->
 call| expect_silent(print("hihi")) 
> expect_silent(print("hihi"), quiet=FALSE)
[1] "hihi"
----- PASSED      : <-->
 call| expect_silent(print("hihi"), quiet = FALSE) 
```
is that a good default?

**Comment by bryanhanson** [comment]
I think that's a good approach.  I will use it to test functions that plot, and occasionally print a message to console.  So conceptually, this is "expect no error no warning" but other output is allowed?  This is really good for "testing the surface".  Thanks!

**Comment by bryanhanson** [comment]
Works perfectly, thank you!
