### ISSUE TITLE
Where at_home() settings are active (vignette clarification about shells)

### ISSUE THREAD

**Issue by bryanhanson** [markvanderloo/tinytest#16]
I'm going to file this under "silly me" but I won't be the only one to misunderstand this, so I recommend some clarification or warning in the vignette.

I was wondering if an `expect_silent` test where I had my flavor of "at_home" in action was being handled correctly.  If I set the `Sys.setenv` appropriately in the R GUI and ran the test interactively, it was clear it was working.  However, if I opened a shell to run `make` using a makefile I always use (for build/check/install --as-cran), I began to think the test wasn't being run.  After a little experimenting, I figured out that I need to set the environmental variable in the new shell as well, using syntax appropriate to the shell.  Otherwise the variable is not seen when the makefile spawns R instances.

In another attempt, I opened a shell, launched R and used `Sys.setenv` to set the variable, quit R, and then tried the makefile.  The variable was not visible in this case either, so I guess R is run in it's own (fresh) shell.

One could correctly say my understanding of when shells are created or spawned and which variables go with them during spawning is limited, but I don't think I'm the only one who does not have a complete understanding of all the things that might happen.  Hence my suggestion for a little warning language in the vignette.

**Comment by bryanhanson** [comment]
So for the record here is how I set it up and documented it for myself, i.e. the contents of a file `test_hats_alignSpectra2D.R`.  With this method the internal `at_home()` function is bypassed.

```
# If running this test interactively:
#   From R, run Sys.setenv("ESTOY_EN_CASA" = "TRUE") to permit additional tests to run
#   From R, run Sys.setenv("ESTOY_EN_CASA" = "") to run exactly as at CRAN

# If running this test via a shell script like a makefile, set the variable in the shell first:
#   setenv ESTOY_EN_CASA TRUE # csh
#   unsetenv ESTOY_EN_CASA # csh
#   export ESTOY_EN_CASA=TRUE # bash
#   export -n ESTOY_EN_CASA # bash

if (identical(Sys.getenv("ESTOY_EN_CASA"), "TRUE")) {
  data(MUD2)
  expect_silent(MUD2a <- hats_alignSpectra2D(MUD2, method = "MBO", debug = 0, plot = FALSE))
}

```

**Comment by markvanderloo** [comment]
That is a valid point. Like you I am surprised that shell commands invoked by `make` apparently do not inherit environment variables from the shell from which `make` was called. I am  'light' user of `make` and certainly not an expert.

**Comment by bryanhanson** [comment]
I get by with `make` but would not claim any significant skill level.

So, using `Sys.setenv()` works interactively, including `test_all()`, `test_dir()` and `build_install_test()`, since all apparently have access to the needed environmental variable.  With that in mind, may I suggest a footnote in the vignette that could read something like:

"Users of makefiles who are using the at_home() feature (or an equivalent) should take care to set the environmental variable in the shell where R CMD check is active."

Naturally, it's up to you.  Maybe @eddelbuettel would have further clarification or suggestions.

**Comment by markvanderloo** [comment]
When you work interactively, you can just use `test_all(...,at_home=FALSE)` (the default is TRUE) and no need to set an environment variable manually. The manual operation is only needed if you want to control the behavior of `test_package()`, and then only when called by `R CMD check` via `tests/tinytest.R`. 

I think I will make an example package where this is done. That would be something to refer to and easier for people to interactively explore.

**Comment by eddelbuettel** [comment]
It so happend that earlier today I just made an off-the-cuff remark to @markvanderloo over DM.  I think some combination about "something detectable as a convention" (_i.e._ I use something like 1.0.1.1 for the first dev version past the 1.0.1 release and then 1.0.1.2, ... 1.0.1.X leading to 1.0.2; the tidyverse / devtools folks copied that scheme [poorly] by making the added digit a sequence starting at 9000) combined with an clear override env var (something like `PACKAGENAME_RUN_ALL_TESTS`).   Something along those lines seems sensible to me.  Location ("honey, I'm home ...") is less attractive to me.

**Comment by markvanderloo** [comment]
Ok, so I did some testing with a `Makefile`, [over here](https://github.com/markvanderloo/dummy). and env vars.

In [tests/tinytest.R](https://github.com/markvanderloo/dummy/blob/master/pkg/tests/tinytest.R) I signal whether the envvar is picked up by writing a timestamp to a file.

Try the following (bash)
```bash
git clone https://github.com/markvanderloo/dummy
cd dummy
export TT_RUN_ALL="TRUE"
make check
cat dummy.Rcheck/tst
```
For me the envvar gets detected, so all tests should run. Have not tried to set it in the make file (could make a new target for that) but I can't see why it would not work (`<--` famous last words)

**Comment by markvanderloo** [comment]
@eddelbuettel I like the `run_all` or `run_all_tests` better than `at_home`. Maybe time to change the `at_home` arguments to `run_all` and `at_home()` to `run_all()`? Would have the same default values. Also, I could indeed add a few functions for detecting 'at home-y-ness'.

**Comment by eddelbuettel** [comment]
I seem to like the few I even pinned down in a [helper script here](https://github.com/eddelbuettel/littler/blob/master/inst/examples/tt.r) --- running a whole package, or directory, or file, or just `test_all()`.  And so far as mentioned I tend do condition within each test file.

**Comment by bryanhanson** [comment]
I can confirm that you can set the variable in the makefile and all works well.
