### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by jeroen** [markvanderloo/tinytest#2]
Interesting package, useful light-weight alternative for testthat. 

One thing that concerns me: as a general rule, it is good practice to only adopt function names from another package if they are implemented as a drop-in replacement. However your readme says:

> __Test functions__
> The syntax of test functions closely resembles that of testthat. The main difference is that the first argument is the desired, and the second argument is the current value.

This will become a cause of confusion and errors when sharing or reading code in which it may be ambiguous which implementation of `expect_equal()` it concerns, or when package authors try to switch between testing frameworks.

I think you should consider either adopting the parameter ordering from testthat, or otherwise rename functions to disambiguate.

**Comment by markvanderloo** [comment]
Yeah, I was thinking about that as well. Will also make it easier for me to convert packages if I keep the order. The pkg currently follows the order of `all.equal`, so that's why.

**Comment by markvanderloo** [comment]
done.
