### ISSUE TITLE
covrpage support for tinytest

### ISSUE THREAD

**Issue by yonicd** [markvanderloo/tinytest#21]
I maintain the [covrpage](https://github.com/metrumresearchgroup/covrpage) package that creates simple human readable files that help communicate the results of unit tests and coverage as part of either GH [readme.md](https://github.com/metrumresearchgroup/covrpage/blob/master/tests/README.md) or a package [vignette](https://metrumresearchgroup.github.io/covrpage/articles/tests_and_coverage.html) making it a transportable product. 

I would like to extend the package to include outputs for tinytest, are there any objects that tinytest returns (list/data.frame) that can be used in a postprocessing workflow?

**Comment by markvanderloo** [comment]
Hi there,

The functions `run_test_dir` `test_all` and `test_package` (the latter when run interactively) all return test data in the form of a `tinytests` object. This can be transformed to a data frame using `as.data.frame` or turned into a table using `summary`. A `tinytests` object is just a list of `tinytest` objects (note: singular). And a `tinytest` object is just a `logical` with attributes. So the structure is.really simple (I hope).

Let me know if you have any particular question, I'm happy to answer them.
