### ISSUE TITLE
How do I collect the full test output of multiple tests in an object

### ISSUE THREAD

**Issue by FvD** [markvanderloo/tinytest#25]
Is  there any way to collect multiple test outcomes to display the diagnostics all at once from the as output from the object where the tests are collected?

This works as I had hoped:

```
> test <- expect_equal(1, 2)
> test
----- FAILED[data]: <-->
 call| expect_equal(1, 2)
 diff| Mean relative difference: 1 
```
But I would like to collect multiple tests in an object (a list?) to show the output at the end of an Rmarkdown file. I tried

```
> mytests <- list()
> mytests <- append(mytests, test)
> mytests
[[1]]
[1] FALSE
```
But this is not the full test output. Is there a way to store that?

**Comment by markvanderloo** [comment]
Hi Frans,

The `tinytest` way is to run your script containing `expect_someting()` calls here and there with
```r
run_test_file("/path/to/your/test_file.R")
``` 
Or, you can modify the above case as follows (I think that 'append' removes attributes):

```
L <- list()
L[[1]] <- expect_equal(1+1, 2)
L[[2]] <- expect_true(1==1)
```
and so on. Using the file runner has the advantage that you get a list of class `tinytests` (note: plural). This is a simply a classed list of test results but it has nice methods for `print`, `summary` and `as.data.frame`.

**Comment by FvD** [comment]
Thanks Mark!

I should have added that I want to use tinytest inside an Rmd file. My first impression was that `tinytest` does no like Rmd too much.

```
> run_test_file("exploracion.Rmd")
Error in parse(file = file, keep.source = TRUE) : 
  attempt to use zero-length variable name
```

This is why I want to collect tests during the execution of the document, and than show the result on a high level at the end, so that I know to have a look at the contents of my test_collection object should I get a warning. 

The indexed list approach works great! I can have an output of all test results in an Annex seccion o the file.  work fine for this use case, and if I only want to have the `TRUE` or `FALSE` I have that with 

I will use named elements in the list like so:

```
L <- list()
L$"test1" <- expect_equal(1+1, 2)
L$"test2" <- expect_true(1==1)
```
With the nice extra that now I can see the full mesage or use `unlist()` to get a named vector
```
> unlist(L)
test1 test2 
 TRUE  TRUE 
```
So I can create a Rmarkdown like warning at the end "Tests ok" or "Be warned, tests failed", and even signal what test (by name) failed.

Thanks again!

**Comment by markvanderloo** [comment]
Ah, that's because an `Rmd` file contains text that is not R code. the `run_test_file` function is like `source`: it runs the whole file, but does something extra (collecting the test results).

Your use case is an interesting one. Maybe there's a way to support it better. I'll keep it in mind.
