### ISSUE TITLE
[Feature Request] Optional message with test predicate?

### ISSUE THREAD

**Issue by eddelbuettel** [markvanderloo/tinytest#27]
For the upcoming term, @barbehenna and I are exploring using `tinytest` to run over sets of test files to assess student answers.  We have a first working prototype (embedded in something larger built by engineering at U of Illinois, see https://github.com/PrairieLearn/PrairieLearn for more) and it is quite nice to work with the resulting object from running tests off a directory.

One facet of the test environment is that feedback given to the student comes from the evaluation of the code.  And we all know that R error messages are not great.  For example, here is our test case of running some (of course!!) `iris` summaries where I (on purpose) omitted some data in the answer to generate an incorrect answer (on a subset of the data):

```
Output
expect_equivalent(as.data.frame(student_res), answer_res, tolerance = 1e-04)
 Component 2: Mean relative difference: 0.0004319478
 Component 3: Mean relative difference: 0.002541568
 Component 4: Mean relative difference: 0.0005738331
 Component 5: Mean relative difference: 0.003801653
```

This works, but could be better in our case.  It exposes the call and details the student does not care about (_i.e._ "what is `expect_equivalent()" ?  what are `student_res` and `answer_res` -- neither is part of what the student submits).  

Can you think of a clever way to either filter this, (optionally) report a message instead?  _E.g._ `RUnit` always had `checkEquals(a, b, msg="Comparing a and b")`.  

Or should we look in some other packages by Edwin and you to _e.g._ diff the `data.frame` in a nicer way?  Any thoughts?   Feel free to close if you think it is feature creep ...

**Comment by markvanderloo** [comment]
Well I have the idea to add an optional `info` field or something that will be printed along with the long message. But it will not replace the long message entirely so there will still be some information that is not relevant to the student.

Better, and perhaps extensible reporting is also still on the list.

You could have a look at the `diffobj` package for a nice way to report differences, or `daff`.

**Comment by eddelbuettel** [comment]
Yes, looking into diff pretty printers is probably a good idea.

**Comment by markvanderloo** [comment]
An info argument was added to `expect` functions in  0ed40c37f13e3ddb4edc50c7eda0f5d36f811ec0
