### ISSUE TITLE
Run a subset of unit tests

### ISSUE THREAD

**Issue by mllg** [markvanderloo/tinytest#29]
Is there a possibility to run only a specific subset of unit tests? `testthat` allows to filter tests based on their filename via `test_dir(..., filter = "[pattern]")`.

**Comment by markvanderloo** [comment]
Yes, here's the signature for `run_test_dir`. The `pattern` argument does the job. 

```r
run_test_dir(dir = "inst/tinytest", pattern = "^test.*\\.[rR]",
       at_home = TRUE, verbose = getOption("tt.verbose", 2),
       color = getOption("tt.pr.color", TRUE), remove_side_effects = TRUE,
       cluster = NULL, lc_collate = getOption("tt.collate", NA), ...)
```

**Comment by mllg** [comment]
Whops, missed that. Thanks for the pointer!
