### ISSUE TITLE
promote tinytest to base R package

### ISSUE THREAD

**Issue by jangorecki** [markvanderloo/tinytest#31]
Any idea if there is a space for promoting tinytest to be a package shipped together with base R?
or eventually its functionality merged into `utils`/`tools` packages?
I also believe that lightweight is the right weight. Because of that I usually keep my tests in scripts in `tests` directory using just simple `stopifnot` checks. This works perfectly well, although I cannot run tests on already installed package.
In the ideal world I would like to have functionality of tinytest to be available in R, without adding extra dependencies, even so tiny, just because `stopifnot` works for me.

**Comment by markvanderloo** [comment]
hypothetically it could theoretically in principle become an R recommended package. But I don't see that happening any time soon. I watched Brian Ripley's keynote in Coventry at 2011. He was clear that 'someone becomes a member of R core when it is more work to keep them out then to let them in'. My feeling is that they do the same with code :-).
