### ISSUE TITLE
Expected and got exchanged in message ?

### ISSUE THREAD

**Issue by billy34** [markvanderloo/tinytest#32]
When for example running this test
``` r
tinytest::expect_equal(0.9-0.7-0.2,0,0)
#> ----- FAILED[data]: <-->
#>  call| tinytest::expect_equal(0.9 - 0.7 - 0.2, 0, 0)
#>  diff| Expected 5.55111512312578e-17, got 0
```
I'm expecting that the message be

    #>  diff| Expected 0, got 5.55111512312578e-17

Am I missing something or are the two values in the wrong order ?

If so looking at the code we can track down the issue in the function `longdiff` where we can find

    sprintf("Expected '%s', got '%s'", current, target)

that should be

    sprintf("Expected '%s', got '%s'", target, current)

**Comment by markvanderloo** [comment]
Thanks for reporting! Fixed in https://github.com/markvanderloo/tinytest/commit/91a332c4e11b7788a54319d45c123be40a3981ee. 
As a small token of appreciation you have been immortalized in the famous [NEWS](https://github.com/markvanderloo/tinytest/blob/master/pkg/NEWS) file.
