### ISSUE TITLE
build_install_test crashes over package directory with spaces

### ISSUE THREAD

**Issue by BartJanvanRossum** [markvanderloo/tinytest#33]
When trying to run the build_install_test function for a package in a directory that contains spaces (on Windows), I get this error:
ERROR
cannot change to directory 'my package dir with spaces'

It happens at the following line in the code:
`system(build_command)`

I know it is a bad idea to use spaces in directory names, but I think it would be nice if it was supported anyway.

**Comment by markvanderloo** [comment]
Dankjewel Bart-Jan! (je naam doet vermoeden dat je NL spreekt :)). Fixed in https://github.com/markvanderloo/tinytest/commit/638e086cf604835bbe56e1507a5c0c9672033234.

Als een klein teken van dank ben je onsterfelijk gemaakt in het [NEWS](https://raw.githubusercontent.com/markvanderloo/tinytest/master/pkg/NEWS) bestand.

**Comment by BartJanvanRossum** [comment]
Dat Nederlands moet wel lukken.

Ik vrees alleen dat het probleem nog niet opgelost is.
Als ik de functie volg krijg ik deze outputs (*** staat voor het package, geen spaties in dat stukje):

```r
pkg <- normalizePath(pkgdir)
"C:\\Projects\\R packages\\***\\"

build_command <- paste0("R CMD build --no-build-vignettes --no-manual ",
                                          gsub(" ", "\\\\ ", pkg))
"R CMD build --no-build-vignettes --no-manual C:\\Projects\\R\\ packages\\***\\"

system(build_command)
 ERROR
cannot change to directory 'C:\Projects\R\'
[1] 1
```

**Comment by markvanderloo** [comment]
Thanks. I need to detect the OS and use `shQuote`. Also I need to set up a test machine running the malware sold as Windows :-).

**Comment by markvanderloo** [comment]
Ok, I think I fixed it in  https://github.com/markvanderloo/tinytest/commit/1bed8c0f023613a08bad82c61e30aa4192b2db65. 
I've had no chance to test it on Windoze but if I read understand the docs, it should all run now. Would be very happy to get a confirmation.

**Comment by BartJanvanRossum** [comment]
Thanks again for the quick changes.
It almost worked now :-)
I had to change `pkg <- normalizePath(pkgdir)` to `pkg <- normalizePath(pkgdir, winslash = "/")` to make it work. Since the winslash argument is ignored on anything but Windows I guess that is a save thing to do.

**Comment by markvanderloo** [comment]
thanks! included in https://github.com/markvanderloo/tinytest/commit/0423e15152214e5603a2ed32f0feda46b61bbc7a

**Comment by BartJanvanRossum** [comment]
Thanks. I can confirm it is working now.

**Comment by markvanderloo** [comment]
Great! Thanks for the confirmation!
