### ISSUE TITLE
Seemingly cannot test function containing `source()`

### ISSUE THREAD

**Issue by eddelbuettel** [markvanderloo/tinytest#34]
Context:  I just set up a baby package [plr](https://github.com/stat430dspm/plr) (that is expected to hopefully grow over time) to help @barbehenna and myself with having R code in [PrarieLearn](https://github.com/PrairieLearn/PrairieLearn) -- where we rely on [tinytest](https://github.com/markvanderloo/tinytest)  to test the student code submitted for evaluation by [PrarieLearn](https://github.com/PrairieLearn/PrairieLearn).  

R being somewhat open is a wee bit of a risk of students snooping around, so we just tied things down (this runs inside Docker) by setting everything to restricted modes and owner/group and just having the submitted file readable for using `unix::eval_safe()` by @jeroen to source and evaluate as the given user.   That use case is our first helper function: `chmod()` a file, `source()` it, determine the (numeric) uid of a user and then evaluate the expression (from the file) safely as the user. 

Problem:  For the life of me I cannot `tinytest` this.  The `source()` call I make inside the very function we are trying to test (_i.e._ the real function, not the test function) always fails on `Error in file.exists(tmp) : invalid 'file' argument`.

Ideas?  Am I being stupid? Or is this a real issue?  You can play with [plr](https://github.com/stat430dspm/plr) and you see in the [line I had to comment out in the one test file](https://github.com/stat430dspm/plr/blob/master/inst/tinytest/test_eval.R#L4).

**Comment by eddelbuettel** [comment]
I think I was being stupid. I was testing facilities from @jeroen 's `unix` package, and those require root permissions which I have of course in the Docker container where I deploy the package ... but not outside where I want to test this.  I think I just can't.

**Comment by markvanderloo** [comment]
Glad that's sorted out. Was out for the weekend and just read the original question.
