### ISSUE TITLE
setup_tinytest removes white space from DESCRIPTION

### ISSUE THREAD

**Issue by BartJanvanRossum** [markvanderloo/tinytest#35]
When running setup_tinytest all the white space in the DESCRIPTION file is removed, even in fields that are not modified, e.g. Authors@R and Description.    
Both read.dcf and write.dcf have an option keep.white that leaves the white space as is. I think it would be good to use these and maybe only write the modified fields to the DESCRIPTION.

**Comment by markvanderloo** [comment]
Thanks, fixed in https://github.com/markvanderloo/tinytest/commit/cc3f3264e54d4981135ed80fef3cfe62e9348526

**Comment by markvanderloo** [comment]
also, there's an easter egg, try `tinytest::puppy("yourpkgname")` to set up a package.

**Comment by BartJanvanRossum** [comment]
Unfortunately not. keep.white doesn't take TRUE/FALSE, but a vector with names of the fields for which 'white' should be kept. Therefore my suggestion to only write (and read) the fields you really need. 
  
I already found the easteregg, after installing from github I ended up with a package without documentation and when scrolling through the functions I wondered what puppy would do. Nice addition!

**Comment by markvanderloo** [comment]
ah, that's what I get for not reading the docs. Will fix a bit later today.

**Comment by markvanderloo** [comment]
I tried it with some dummy pkgs and it should be better now since https://github.com/markvanderloo/tinytest/commit/57a428fe7980cb1f469e2ada3a937811bc108860

**Comment by markvanderloo** [comment]
Regarding installing from GH: I almost never put the `/man` directory under version control since it is generated by `roxygen2` anyway. I find it annoying to manually add/remove `.Rd` files to git tracking when I add/remove/rename a function.

**Comment by BartJanvanRossum** [comment]
I think you are missing "Suggests" in kw.

With that it is working for my package. However I think almost all fields may contain whitespace, so it might be safest to first read the full file without restrictions and then use all column names of the file you read as keep.white in a second run. Since read.dcf is very fast I guess there is not much to loose here.

Also I noticed you use `pkgname <- dcf[1]` to get the package name. That works fine as long as people put their package name on the first line of the DESCRIPTION file. This `dcf[, "Package"]`might be safer.

**Comment by markvanderloo** [comment]
Thanks, done and done. In master branch now.
I did not try to keep.white="Suggests" because I figured since I am manipulating that field, I'm not sure what the outcome will be.

**Comment by BartJanvanRossum** [comment]
Thanks for the quick changes.

It looks like this now:
![afbeelding](https://user-images.githubusercontent.com/28725410/64510030-60803400-d2e1-11e9-9c9c-755a2e6e06ed.png)

I think that is just fine
