### ISSUE TITLE
tinytest and Rcpp (Attributes) are not playing along

### ISSUE THREAD

**Issue by eddelbuettel** [markvanderloo/tinytest#37]
My plan of switching the Rcpp family to tinytest hit the skids on the first test I tried for RcppArmadillo.

In  a nutshell, an existing test file [like this one for RUnit](https://github.com/RcppCore/RcppArmadillo/blob/master/inst/unitTests/runit.complex.R) has a call to on-demand compile a C++ file with the C++ side of the tests.  We use an in-package helper function for that in Rcpp and RcppArmadillo, but mostly only because RUnit is not as clever as tinytest about where it runs.

So then for tinytest, I just tried 

```c++
library(RcppArmadillo)

Rcpp::sourceCpp("cpp/complex.cpp")

## tests below
```

which "should just work" -- and does indeed on the command-line with either the file or directory runner:

```sh
edd@rob:~/git/rcpparmadillo(feature/tinytest)$ tt.r -f inst/tinytest/test_complex.R 
Running test_complex.R................   11 tests OK 
[1] "All ok, 11 results"
edd@rob:~/git/rcpparmadillo(feature/tinytest)$ tt.r -d inst/tinytest/
Running test_complex.R................   11 tests OK 
[1] "All ok, 11 results"
edd@rob:~/git/rcpparmadillo(feature/tinytest)$ 
```

But when I let `R CMD check` loose, all hope is lost, and I get an error message I do not think I have ever seen before (!!):

```sh
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘doRUnit.R’
  Running ‘tinytest.R’
 ERROR
Running the tests in ‘tests/tinytest.R’ failed.
Last 13 lines of output:
  Calls: local ... eval.parent -> eval -> eval -> eval -> eval -> source -> file
  In addition: Warning message:
  In file(filename, "r", encoding = encoding) :
    cannot open file 'startup.Rs': No such file or directory
  Execution halted
  
  Error in Rcpp::sourceCpp("cpp/complex.cpp") : 
    Error 1 occurred building shared library.
  Calls: <Anonymous> ... run_test_dir -> lapply -> FUN -> eval -> eval -> <Anonymous>
  
  WARNING: The tools required to build C++ code for R were not found.
  
  Please install GNU development tools including a C++ compiler.
  
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
```

No C++ compiler? Really?  Could it be that tinytest set things up so tight that certain maintained assumptions no longer hold?

**Comment by eddelbuettel** [comment]
FWIW same behaviour on 1.0.0 and 1.0.0.7.

**Comment by markvanderloo** [comment]
Ha..have a quick look at #36

**Comment by eddelbuettel** [comment]
I had. But I suspect that is not it.  Blows up with `ncpu=NULL` as well.

**Comment by eddelbuettel** [comment]
Tried again. No impact.  Still fails.  :cry:

**Comment by eddelbuettel** [comment]
Attached is a trimmed-down version of the package (no `vignettes/`, no `RUnit` use). It has the one test failing. Maybe you can dive into `tinytest` and see why running the test file 'directly' works but checking the package does not?

[RcppArmadillo_0.9.700.2.0.1.tar.gz](https://github.com/markvanderloo/tinytest/files/3613150/RcppArmadillo_0.9.700.2.0.1.tar.gz)

**Comment by eddelbuettel** [comment]
I think I got it.  We need two things, and I had only done _one_ at a time (doh)

- your hunch is correct, one does need `R_TESTS=""` as an environment variable; that is an R constant
- one the _also_ needs to tell `tinytest` to _not_ mess with environment variables, _i.e._ to *not* check for side effects

That seems to work.  :cake: 

Medium-term, I see two things:

- you may as well set `R_TESTS=""` for everybody as a courtesy (and just document it)
- if you don't want to do that then I think you need to tell the side effects checker routine to leave `R_TESTS` alone

**Comment by eddelbuettel** [comment]
Here is a better version proving that theory (the .1 above had one other wart)

[RcppArmadillo_0.9.700.2.0.2.tar.gz](https://github.com/markvanderloo/tinytest/files/3613198/RcppArmadillo_0.9.700.2.0.2.tar.gz)

**Comment by eddelbuettel** [comment]
And parallel tests work fine too.

**Comment by markvanderloo** [comment]
Wow, thanks for all that work! I haven't had a chance this weekend to look into it. But this is something I can definitely work with.

**Comment by eddelbuettel** [comment]
All works wonders for me _if and only if_ I turn side-effects off.  `R_TESTS=""` is in fact needed, so I think you should think hard about making it a default. I don't think there are side-effects, but we can test.  AFAIK *every* unit test framework has fallen into this hole because `R CMD check` is so tight about the path.

Otherwise, `tinytest` is glorious.  Look at this:

```sh
edd@rob:~$ tt.r -p RcppArmadillo
starting worker pid=6475 on localhost:11311 at 13:17:36.362
starting worker pid=6502 on localhost:11311 at 13:17:36.509
starting worker pid=6543 on localhost:11311 at 13:17:36.650
starting worker pid=6568 on localhost:11311 at 13:17:36.790
Running test_rng.R....................   10 tests OK 
Running test_complex.R................   11 tests OK 
Running test_sample.R.................   21 tests OK 
Running test_cube.R...................   18 tests OK 
Running test_fastLm.R.................   25 tests OK 
Running test_rcpparmadillo.R..........   48 tests OK 
Running test_Rlapack.R................    7 tests OK 
Running test_scipy2r.R................    4 tests OK 1 side-effects
Running test_rmultinom.R..............    9 tests OK 
Running test_sparse.R.................   12 tests OK 
Running test_sparseConversion.R.......   86 tests OK 
----- SIDEFX[envv]: test_scipy2r.R<33--33>
 call| if (!py_module_available("scipy")) exit_file("Module scipy missing")
 diff| Added   envvar 'R_SESSION_INITIALIZED' with value 'PID=6568:NAME="reticulate"'
 diff| Added   envvar 'RETICULATE_REQUIRED_MODULE' with value 'scipy'
 diff| Changed envvar 'PATH' from '/home/edd/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' to '/usr/bin:/home/edd/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
 
Showing 1 out of 252 results: 0 fails, 251 passes, 1 side effects
edd@rob:~$ tt.r -pz RcppArmadillo
starting worker pid=7234 on localhost:11807 at 13:17:43.703
starting worker pid=7261 on localhost:11807 at 13:17:43.846
starting worker pid=7301 on localhost:11807 at 13:17:43.987
starting worker pid=7327 on localhost:11807 at 13:17:44.132
Running test_complex.R................   11 tests OK 
Running test_rng.R....................   10 tests OK 
Running test_sample.R.................   21 tests OK 
Running test_cube.R...................   18 tests OK 
Running test_fastLm.R.................   25 tests OK 
Running test_rcpparmadillo.R..........   48 tests OK 
Running test_Rlapack.R................    7 tests OK 
Running test_rmultinom.R..............    9 tests OK 
Running test_scipy2r.R................    4 tests OK 
Running test_sparse.R.................   12 tests OK 
Running test_sparseConversion.R.......   86 tests OK 
[1] "All ok, 251 results"
edd@rob:~$ 
```

And I can't even sheepishly try to 'undo' the env var settings that `reticulate` causes as you;d catch me :).  This is truly fabulous stuff.

**Comment by markvanderloo** [comment]
Found [this note](https://github.com/HenrikBengtsson/startup/issues/19) by @HenrikBengtsson. Looks like currently, `R_TESTS` is only used to define a new startup file `startup.Rs` which currenlty only sets the `useFancyQuotes` option to `FALSE`. This is something that can easily be mocked without disturbing `R CMD check`, but we need to watch it for changes. 

Also, I have to make sure this is done for all parallel sessions in case of parallel testing.

**Comment by eddelbuettel** [comment]
Yes. See the `grep` / `ag` snippets I sent you over slack.  Both say the same thing. And as usual, what 
@HenrikBengtsson says is of cause more useful and useable than my ramblings :grin:

**Comment by markvanderloo** [comment]
Fixed in https://github.com/markvanderloo/tinytest/commit/0ab06593a51029a44a644c46f890fd424302077c and tested on `RcppArmadillo`. Also affects #36
