### ISSUE TITLE
run_test_dir runs too many files

### ISSUE THREAD

**Issue by eddelbuettel** [markvanderloo/tinytest#38]
Certain editors leave backup files around which are the same as the original name, pleae, say `~`.  So after editing `test_foo.R` I may have `test_foo.R~`.

But in 

```r
run_test_dir <- function(dir="inst/tinytest", pattern="^test.*\\.[rR]"
```

the pattern is too greedy.  Just making it `pattern="^test.*\\.[rR]$"` should fix this.  

I can send a PR if you want.

**Comment by markvanderloo** [comment]
Thanks, fixed it.

**Comment by eddelbuettel** [comment]
Any other place that needs looking at?  I didn't have time to really dig ...

**Comment by markvanderloo** [comment]
I don't think so, but I'll have a look and rev Dept test before release
