### ISSUE TITLE
[Feature Request] Add invisible to run_test_dir ?

### ISSUE THREAD

**Issue by eddelbuettel** [markvanderloo/tinytest#4]
Change is (of course) trivial but before lobbing a PR I'd thought I'd propose it. 

I had been running the function a bit while testing and the default `print` method invocation is a wee bit noisy for my taste. Yay? Nay?

Also had one good idea for an actual improvement but have to noodle with that first...

**Comment by markvanderloo** [comment]
You can already pass `verbose=FALSE`. Is that what you mean?

**Comment by eddelbuettel** [comment]
I'll post a demo here of what I meant, maybe this eve or tomorrow.

**Comment by eddelbuettel** [comment]
The change I have on my laptop is simple:

```diff
diff --git a/pkg/R/tinytest.R b/pkg/R/tinytest.R
index 4d05bfb..3619c6c 100644
--- a/pkg/R/tinytest.R
+++ b/pkg/R/tinytest.R
@@ -536,7 +536,7 @@ run_test_dir <- function(dir="inst/tinytest", pattern="^test.*\\.[rR]"
   for ( file in testfiles ){
     test_output <- c(test_output, run_test_file(file,at_home=at_home, verbose=verbose, color=color))
   }
-    structure(test_output,class="tinytests")
+  invisible(structure(test_output,class="tinytests"))
 }
 ```

**Comment by eddelbuettel** [comment]
I looks like I can no longer trigger the behavior I saw earlier.  So maybe it was due to the `options()` values I had chosen.  So I guess a case of never mind...

**Comment by eddelbuettel** [comment]
What I was seeing must have been transient with 0.9.2 or my options settings (which were eager -- I later realized defaults to the Right Thing (TM) which is cool) so closing this.   _We apologize for any invonvenience caused._  ;-)

**Comment by markvanderloo** [comment]
Ah, cheers for the clarification :-). 

I'm happy that my strategy of _management by waiting around_ works, as always, beautifully ;-)
