### ISSUE TITLE
testing the working directory

### ISSUE THREAD

**Issue by majazaloznik** [markvanderloo/tinytest#45]
it seems it isn't possible to test the current working directory, since the call to `getwd()` inside a test function returns the directory in which the testing script is saved. 

is this intentional and is there a possible workaround?

**Comment by markvanderloo** [comment]
Apologies for the late reply.

I'm not sure how to reproduce your question. I did a quick test with the '/inst/tinytest' directory of `stringdist` and doing `run_test_dir("./")` worked fine (after loading `stringdist` and `tinytest`). Could you provide a bit more information?

**Comment by majazaloznik** [comment]
Sorry for not being clear. What I meant was that if I have a project or package in the folder `/my_project` and a test file `test.R` in the folder `/my_project/tests/` that contains the following line:

`expect_equal(getwd(), "/my_project")`

The test fails, since `getwd()` is returning `/my_project/tests/` i.e. the location of the test file. 

Does that make sense? And if i have this right, how might one go about testing the session wd? Cheers!

**Comment by markvanderloo** [comment]
Ah, now I get it. Yes, `tinytest` temporarily switches working directory while executing the test (this is safe because switching back is done via `on_exit()`. So it does what is expected.

Base R has two functions that may help you:
```{r}
basename()
```
returns the last part of a directory path, and
```{r}
dirname()
```
returns everything except the last part of a directory path


Also, to set up your package with `tinytest`, you can use the following easter egg:

```r
tinytest::puppy("/path/to/pkg/directory")
```

**Comment by majazaloznik** [comment]
Ah, ok, so it's expected behaviour, thanks for that, and the easter egg ;)

But I'm not sure how `basename()` or `dirname()` can help me here. I would like to know what the working directory was before it switched to the test, or where it will switch back to on.exit(), is that possible to check?

**Comment by markvanderloo** [comment]
Ah, if you want to know the working directory from where `run_test_dir` was called, I don't think that's possible. At least `tinytest` does not support that.

I have to think if that can be made accessible somehow by the package. It seems like a good service.

Thanks for the idea.

**Comment by markvanderloo** [comment]
Hi Maja, I have added a function called `get_call_wd` that returns the directory from where `run_test_dir` (or one of its siblings) was called. I'd be grateful if you'd give it a spin and let me know how it works.
