### ISSUE TITLE
expect_message() / expect_output()

### ISSUE THREAD

**Issue by mllg** [markvanderloo/tinytest#49]
During migration from testthat to tinytest, I was missing a function which tests for regular output (i.e., to stdout like `cat()` instead of stderr like `message()`).

Side note: After looking at the code of `expect_message()`, I'm also wondering why messages are not caught via `tryCatch(..., message = function(m) ...)`?

**Comment by markvanderloo** [comment]
Good point. I'm not sure about my reasoning at the time. `expect_message` currently also catches output sent to `stdout`, using `sink` (as you've seen). I iirc, I stole that idea from the implementation of `capture.output`. 

Adding a function to just catch `stdout` is a good idea. Will do.

**Comment by markvanderloo** [comment]
added a new function called `expect_stdout`. Closing this now.
