### ISSUE TITLE
expect_message()/expect_warning()/expect_error()

### ISSUE THREAD

**Issue by mllg** [markvanderloo/tinytest#50]
R supports typed conditions, e.g. `requireNamespace()` creates errors of class `"packageNotFoundError"`. It would be helpful if all `expect_` function could optionally test for a specific class of a condition (`testthat::expect_error()` has argument `class` for this).

**Comment by markvanderloo** [comment]
That's a great idea, thanks!

**Comment by markvanderloo** [comment]
added `class` argument` to `expect_error/warning/message`. Closing now
