### ISSUE TITLE
`expect_message()` tests for `pattern` only on the first message that is produced by `current`

### ISSUE THREAD

**Issue by ikosmidis** [markvanderloo/tinytest#53]
The below seems like a slightly unexpected behaviour from `expect_message()` when looking for`pattern` in multiple messages produced by `current`:

The below works as expected
``` r
library("tinytest")
expect_message({message("a minor"); message("issue")}, pattern = "minor")
#> ----- PASSED      : <-->
#>  call| expect_message({
#>  call| message("a minor")
#>  call| message("issue")
#>  call| }, pattern = "minor")
```

I'd expect the following test to pass
``` r
library("tinytest")
expect_message({message("a minor"); message("issue")}, pattern = "issue")
#> ----- FAILED[xcpt]: <-->
#>  call| expect_message({
#>  call| message("a minor")
#>  call| message("issue")
#>  call| }, pattern = "issue")
#>  diff| The message message
#>  diff| 'a minor
#>  diff| '
#>  diff| does not match pattern 'issue'
```

Perhaps, a side-effect of using `tryCatch`?

**Comment by markvanderloo** [comment]
Hi there,

Are you sure you have version 1.2.1?

This case is part of the test suite and I don't get the issue: https://github.com/markvanderloo/tinytest/blob/master/pkg/inst/tinytest/test_gh_issue_51.R

**Comment by ikosmidis** [comment]
Indeed. I was still on 1.2.0. I confirm that 1.2.1 fixed it. Thanks.
