### ISSUE TITLE
Should be able to specify file pattern in build_install_test()

### ISSUE THREAD

**Issue by pbreheny** [markvanderloo/tinytest#54]
In `run_test_dir()`, there is an option, `pattern`, to specify which file patterns contain testing scripts.  However, this option is not present in `build_install_test()`.

**Comment by markvanderloo** [comment]
Thanks for reporting Patrick, I fixed it in the development version.

I'd be grateful if you could take it for a spin and report if it works for your use case.

**Comment by pbreheny** [comment]
Works great -- thanks for the quick fix, and for the excellent package!

**Comment by pbreheny** [comment]
Actually, having worked with this a bit further, there's an issue with regular expressions, in the sense that in your implementation, they go through an additional round (rounds?) of parsing.  For example,

```r
build_install_test(testdir='tests', pattern='.*\\.R')
```

fails:

```
Error: '\.' is an unrecognized escape in character string starting "'.*\."
```

Not the end of the world, but could lead to confusion on the part of users, since that same pattern *does* work in `run_test_dir()`.

I'll reopen and let you decide whether you want to work on this further or not.

**Comment by markvanderloo** [comment]
Thanks, I missed that. Just fixed it in https://github.com/markvanderloo/tinytest/commit/ebfa80d899f61ba3a66191589d2f352dddced670
