### ISSUE TITLE
expect_equivalent_to_reference file path

### ISSUE THREAD

**Issue by TFcfgo** [markvanderloo/tinytest#55]
Is it necessary for the reference file to live in the tinytest folder?

When trying to reference to a file (e.g. with `system.file()`) in a different folder I always run into errors in my R-CMD Check (on Windows). I have mutliple files to reference to and splitting those from my r test files could yield much better overview.

**Comment by markvanderloo** [comment]
Hi there. No it is not necessary for files to live in the tinytest folder. I'm not sure what error you are seeing, but note that (per `?expect_equivalent_to_reference`)

```
Be aware that on CRAN it is not allowed to write data to user
     space. So make sure that the file is either stored with your
     tests, or generated with ‘tempfile’, or otherwise make sure that the test is skipped on
     CRAN, using ‘at_home’.
```

**Comment by TFcfgo** [comment]
Ah thanks! That was all I needed. My mistake was using `system.file("inst/path", "filename.rds", package = "mypackage")` which worked locally and with `tinytest::test_all()` but after package installation in R CMD check the folder could not be found anymore.
