### ISSUE TITLE
Feature request Mocking

### ISSUE THREAD

**Issue by thfuchs** [markvanderloo/tinytest#56]
Are the any plans integrating mocking functions like `testthat::with_mock`?

**Comment by markvanderloo** [comment]
Hi there, it appears that `with_mock` is [on its way out](https://testthat.r-lib.org/reference/with_mock.html).

However, I think you can use the `mockr` or `mockery` package within `tinytest` (disclaimer: never tried it). In principle, you need to put either of those packages in `Suggests:` and use load it in you test file(s).

**Comment by TFcfgo** [comment]
Hey,

specifically for database tests I've found [`dittodb`](https://github.com/ropensci/dittodb) working best. It's capturing responses from database connections (whether table exists, list of tables and results of some further sql commands related to your task).
Your tests then always run against these mocked database results until you capture again.

They use `testthat` by default though adding a path like "inst/dittdb/" in `start_db_capturing()` to have captured responses next to the tinytest folder works perfectly fine.

Also as you suggested just adding `dittodb` to `Suggests` in `Description` and `tests/tinytest.R`.

The only difference in testing then is to run `tinytest` functions in `with_mock_db()`

**Comment by TFcfgo** [comment]
Obviously I celebrated the success too early...When running the tests in R cmd check the mocking files are not found. I'll work on this!

**Comment by markvanderloo** [comment]
Thanks for the updates Tomas.

When working with files under /inst, there are two things to take care of.

- A directory `/inst/foo/` will be installed as `foo/`. And that's what you need to use at `R CMD check` time.
- you are not allowed to write there. Always use a `tempfile()` for writing. (Tests that run under `/tests` are allowed to write locally, as `/tests` is not installed. You can configure tinytest to have tests under say, `tests/tinytest` as well.)

**Comment by TFcfgo** [comment]
Thanks for this hint! Using `with_mock_path()` instead of `with_mock_db()` and specifying path without `inst` works fine when running tests directly and with `R CMD check`

In the test scripts, I now have
```r
with_mock_path(path = "dittdb/", {
    # <unit tests which rely on database connections>
})
```

These unit tests then do not query any database nor write anything but look for dittodb-R files in `inst/dittodb` and run the tests with priviously saved database results.

**Comment by markvanderloo** [comment]
Thanks for all this work, and great to hear that it runs now!

We should definitely write this up in the vignette with a reference to your package as an example.

**Comment by TFcfgo** [comment]
Yes if you could leave the issue still open I could wrap it up  
To `using_tinytest`?

**Comment by markvanderloo** [comment]
Yes, that would be great. Thanks!
