### ISSUE TITLE
Internal function with triple-colon not working

### ISSUE THREAD

**Issue by nordicgit70** [markvanderloo/tinytest#59]
Hi, at first thanks for the great work on this test package.

I developed internal functions with tinytests that execute fine with `tinytest::test_all()` (after `devtools::load_all()`). However the test fail when using `devtools::check(args = c('--as-cran'))`. I tried to resolve this by using triple-colon for the function calls in the tests, which also works fine with `tinytest::test_all()`. 

The issue is that adding triple-colon results in a failure with `test_check("the_package_name")` reporting "Error: No tests found for the_package_name". It looks like the tests can no longer be found.

Can this be an issue with tinytest?

**Comment by markvanderloo** [comment]
Hi, apologies for the late reply.

I use the triple colon to test internals in the validate package w/o problems, so I don't think it's a problem with tinytest: [see here](https://github.com/data-cleaning/validate/blob/master/pkg/inst/tinytest/test_parse.R).

I'm not sure if it may have anything to do with `devtools`. I always use `R CMD check --as-cran` directly on the CLI so I'm sure I do the same as `CRAN` does.

**Comment by nordicgit70** [comment]
Hi, thanks for your help.
The issue was caused by a `testthat` snippet that was left in the test folder. 
After removing it things are working fine.
