### ISSUE TITLE
Interactive vs Package Checking (scope/environment issue?)

### ISSUE THREAD

**Issue by bryanhanson** [markvanderloo/tinytest#6]
### Minimal Example

The following code works just fine interactively:
```
library("tinytest")
set.seed(1)
vec <- rnorm(10)
expect_warning(log(vec), "NaNs produced")
```
But if I put it in a package, it fails because it cannot find `vec`.
```
* checking tests ...
  Running 'tinytest.R'
 ERROR
Running the tests in 'tests/tinytest.R' failed.
Complete output:
  > if (require(tinytest, quietly = TRUE)) test_package("ChemoSpec2D")
  
  Running test_MWE.R (00|00|00)
  Running test_MWE.R (00|00|00)
  Running test_MWE.R (00|00|00)Error in eval(expr, envir = e) : object 'vec' not found
  Calls: test_package ... expect_warning -> fun -> withCallingHandlers -> eval -> eval
  Execution halted
```
### More Elaborate Example
As you can see I am testing my package `ChemoSpec2D`.  The first example is a toy example that I put in the package temporarily.  I'm attaching a file which represents a real test (attached as .txt as Github will not allow .R extensions).  In this test there are actually two tests, both using variables created in the test script.  One test can find the variable it needs, the other cannot (and the order of tests does not matter).  The check process reports, in this case:
```
* checking tests ...
  Running 'tinytest.R'
 ERROR
Running the tests in 'tests/tinytest.R' failed.
Last 13 lines of output:
  Running test_centscaleSpectra2D.R (01|00|01)
  Running test_centscaleSpectra2D.R (01|00|01)
  Running test_centscaleSpectra2D.R (01|00|01)
  Running test_centscaleSpectra2D.R (01|00|01)
  Running test_centscaleSpectra2D.R (01|00|01)
  Running test_centscaleSpectra2D.R (02|01|01)
  Running test_centscaleSpectra2D.R (03|02|01)
  Running test_centscaleSpectra2D.R (04|03|01)
  Error: ----- FAILED[xcpt]: test_centscaleSpectra2D.R<24--26>
   call expect_error(centscaleSpectra2D(tiny, center = TRUE, scale = "log"), 
   call "Cannot take log of centered data")
   diff The error message:
   diff 'object 'tiny' not found'
   diff does not match pattern 'Cannot take log of centered data' 
  Execution halted
```
As the testing environment for `ChemoSpec2D` is a bit complicated, I'm not including detailed information about it just now. Hopefully the information provided is enough to troubleshoot.  If not, I can push current code to a repo.

I included the second example but it seems really strange that one variable is visible and another is not.

Maybe it is as simple as I am doing something wrong here(?).

Thanks, Bryan
```
> sessionInfo()
R version 3.6.0 Patched (2019-05-19 r76539)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] tinytest_0.9.3

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0   
```
[test_centscaleSpectra2D.txt](https://github.com/markvanderloo/tinytest/files/3203882/test_centscaleSpectra2D.txt)

**Comment by markvanderloo** [comment]
Hi, thanks for your interest in the package.

I stumbled upon this recently myself, and I think I have now solved it in the development version.

Could you try
```bash
git clone https://github.com/markvanderloo/tinytest
cd tinytest
./document.sh
./build.sh
R CMD INSTALL output/tinytest_0.9.4.tar.gz
```
and then rerun your tests?

**Comment by bryanhanson** [comment]
Thank you Mark.  That does indeed fix things (your original version, did not try the drat version). 

I really like `tinytest` - thanks for creating it.  Lean footprint, simple to write tests, clear error messages.

Do you know approximately when your next submission to CRAN will be?  I've got three related packages that I hope to get to CRAN within a week or so, would be great if the latest `tinytest` was waiting there for me!

**Comment by markvanderloo** [comment]
Glad you like it!
My plan is to send 0.9.4 it to `CRAN` before end of next week (and the end of next week is on Wednesday here, because of a bank holiday). 

I have now uploaded a new version to the drat repo that has better output printing, especially when you program over tests, e.g.

```r
if (at_home()){
  expect_true(1==1)
  expect_equal(1+1,3) # note the error
}
# or

for ( i in 1:10 ){
  expect_equal( 1 + 1,2)
}
```

If you have such cases, I'd be interested in your opinion (if not, no worries). You can set 
```r
options(tt.pr.passes=TRUE)
```
so passing tests are also printed.

**Comment by bryanhanson** [comment]
I want to try the `at_home` feature, but it's going to have to wait for the next release.  I'll close this since the original issue was fixed.  Thank you so much.
