### ISSUE TITLE
add expect_inherits()

### ISSUE THREAD

**Issue by bastistician** [markvanderloo/tinytest#67]
This is a follow up from https://github.com/markvanderloo/tinytest/issues/28#issuecomment-722638028, where I wrote:

> I don't have a strong opinion on the need for expect_inherits. It is easy to emulate using expect_true, but being a very common test (I guess), a dedicated expectation for that could be worthwhile.

I now did a meta analysis of 4951 CRAN packages suggesting **testthat** and found that 1686 (34%) used at least one of `expect_is`, `expect_s3_class` or `expect_s4_class`. IMO, this proportion is large enough to justify a predefined `expect_inherits` expectation in **tinytest**.

FWIW, my current workaround is to define the following wrapper function in `tests/tinytest.R` (this approach is fine *only* as long as tests are run via this file, i.e., essentially for R CMD check):
```r
expect_inherits <- function (current, class, info = NA_character_) {
    ## find captured expectation function from tinytest::run_test_file
    expect_true <- get("expect_true", parent.frame(), inherits = TRUE)
    ## with tinytest::expect_true(), these tests would silently be ignored!
    expect_true(inherits(current, class), info = info)
}
```

I guess an alternative solution would be to allow the **tinytest** user to define such customized / composite expectations in a setup file as discussed in #28.

**Comment by markvanderloo** [comment]
Thanks! I'll add an `expect_inherits` soon and then release.

**Comment by markvanderloo** [comment]
Added in https://github.com/markvanderloo/tinytest/commit/e3d00f93bd9ec6dcef6b29ff59eb9d183559b1ab

**Comment by bastistician** [comment]
Thank you! I can confirm this works as intended (I tested both failure and success).

The new helper function `class_string()` seems like a leftover?

**Comment by markvanderloo** [comment]
Yes that's a leftover. Will remove, cheers!
