### ISSUE TITLE
Return innermost call

### ISSUE THREAD

**Issue by lindeloev** [markvanderloo/tinytest#70]
Say I have this in `test-example.R`:

```r
inner_func = function() {
  expect_true(TRUE)
  expect_true(FALSE)
}

outer_func = function() {
  inner_func()
}

outer_func()
```

Then I think it would be most helpful to learn that the test failed at line `expect_true(FALSE)` rather than `outer_func()`.

```r
> tinytest::run_test_file("inst/tinytest/test-example.R")
Running test-example.R................    2 tests 1 fails 2ms
----- FAILED[data]: test-example.R<10--10>
 call| outer_func()
 diff| Expected TRUE, got FALSE
```

I am trying out `tinytest` for the [mcp package](https://github.com/lindeloev/mcp). The test suite is basically a list of many different models with the same test functions being run for each of them. My call stack goes to 3 or 4 levels. As a work-around, I could add a unique identifier like `expect_true(TRUE, info = "inner_func() expect_true(FALSE)")`, but this duplicates code.

Thanks for a great package!

**Comment by markvanderloo** [comment]
Interesting case.

Technically, `outer_func()` is the line in the file triggering the test. In this case, the difference report
```r
diff| Expected TRUE, got FALSE
```
does lead you uniquely back to `expect_true(FALSE)` in `inner_func()` but I can see where things can go wrong.

`tinytest` currently does not pick up the whole call stack but it is something that I'll seriously consider.

I think your best option right now is to give a meaningful `info` field. If you use tests inside loops, you can even create them on the fly so you know exactly in which iteration of the loop things go wrong. I would not include the call stack manually in `info`. Any string that allows you to find the test is in principle fine. But if you want to, you can use `Sys.call()` to get the current call stack, turn that into a string and add it to the info field.

**Comment by markvanderloo** [comment]
**update**
I think it is quite easy to implement. Will do.

**Comment by lindeloev** [comment]
Great! `Sys.call()` returns the innermost function but does not single out the `tinytest::func` that failed. Maybe I'm just doing it wrong with ~ 40 tests in one of my inner functions, but it would be nice if I could quickly see which one failed. Something that produced an output like

```r
expect_true = function(current, info = NA_character_) {
  call_str = deparse(sys.calls()[[sys.nframe()]])
  call_str = gsub(",( |)+info( |)+=.*", "", call_str)
  cat(" call|", call_str, ")")
  if (current == FALSE) {
    cat("\n info|", info)
  }
}
```

Console output:
```
> expect_true("goat" == "horse", info = "was not a horse")
 call| expect_true("goat" == "horse" )
 info| was not a horse
```

**Comment by markvanderloo** [comment]
Current status. I have this test file called `x.R`

```r

myf <- function(n){
  expect_equal(1,n)
} 

myf2 <- function(m){
  myf(m+1)
}

x <- expect_equal(1,2)

myf2(0)
myf2(1)


for ( i in -2:2 ){
  myf2(i)
}


expect_equal(1,1)

expect_equal(2,9)
```
and if I run that, you get a stack trace, but only the meaningful part of the trace, and only when there is a trace to be given.

```r
> library(tinytest)
> run_test_file('x.R')
x.R...........................   10 tests 7 fails 55ms
----- FAILED[data]: x.R<10--10>
 call| expect_equal(1, 2)
 diff| Expected 2, got 1
 ----- FAILED[data]: x.R<13--13>
 call| expect_equal(1, n)
 diff| Expected 2, got 1
 ----- FAILED[data]: x.R<16--18>
 call| myf2(i)
 call| -->myf(m + 1)
 call| -->expect_equal(1, n)
 diff| Expected -1, got 1
 FAILED[data]: x.R<16--18> myf2(i)...
 FAILED[data]: x.R<16--18> myf2(i)...
 FAILED[data]: x.R<16--18> myf2(i)...
 FAILED[data]: x.R<23--23> expect_equal(2, 9)
 
Showing 7 out of 10 results: 7 fails, 3 passes (55ms)

```
