### ISSUE TITLE
MINOR: grDevices::pdf(file=nullfile())

### ISSUE THREAD

**Issue by HenrikBengtsson** [markvanderloo/tinytest#71]
Instead of using `tempfile()` you could avoid hitting the file system by using `nullfile()` in:

https://github.com/markvanderloo/tinytest/blob/39930ea9ae62367dc2f9285dd49dfe0891ab49ef/pkg/R/tinytest.R#L531-L532

`base::nullfile()` was added in R 3.6.0, so you'd have to define it locally for older versions;

```r
if (!exists("nullfile", mode = "function", envir = baseenv())) {
  nullfile <- function() if (.Platform$OS.type == "windows") "nul:" else "/dev/null"
}
```

**Comment by markvanderloo** [comment]
Thanks, that's a good suggestion. Will do. I'll define `nullfile()`  like I do with `isFALSE()` to avoid depending on an R version.
