### ISSUE TITLE
run_test_file() resets environment variables set by test script to empty string when they should be unset

### ISSUE THREAD

**Issue by HenrikBengtsson** [markvanderloo/tinytest#75]
Similarly to what was fixed in #72/#73:

```r
> Sys.getenv(c("USER", "FOO"), unset = NA_character_)
USER  FOO 
"hb"   NA 

> cat("Sys.setenv(USER='foo', FOO='bar')", file = { tf <- tempfile() })
> tinytest::run_test_file(tf)
file7ce62a2293e5..............    0 tests    43ms
All ok, 0 results (43ms)

> Sys.getenv(c("USER", "FOO"), unset = NA_character_)
USER  FOO 
"hb"   "" 
```

To fix this, one needs to call `Sys.unsetenv()` on those non-existing variables.

PS. Good that you caught commit/534cafc5b1 - I was just about the PR that mistake of mine.

**Comment by markvanderloo** [comment]
I'm using `Sys.unsetenv()` in `pkg/R/tintest.R`, but the behaviour is OS-dependent, from `?unsetenv`:

> On Unix-alikes, if ‘Sys.unsetenv’ is not supported, it will at
     least try to set the value of the environment variable to ‘""’,
     with a warning.

So less then desirable, as you may depend on a variable existing rather than a variable having a certain value, but it seems the best we can do.
