### ISSUE TITLE
declare minimum R version

### ISSUE THREAD

**Issue by bastistician** [markvanderloo/tinytest#77]
This is motivated by the following comment:

> I'll define `nullfile()`  like I do with `isFALSE()` to avoid depending on an R version.

_Originally posted by @markvanderloo in https://github.com/markvanderloo/tinytest/issues/71#issuecomment-786166568_

I got interested to check on which version of R **tinytest** actually depends. My conclusions are:

- an absolute minimum is R 3.0.0, because `run_test_file()` works with source references from `parse()`

- **tinytest** currently implicitly relies on R >= 3.2.0, because it uses `dir.exist()` and `trimws()`.

If **tinytest** wanted to support R 3.0.0--3.1.3, it needs to define replacements for `dir.exist()` and `trimws()` conditionally on `getRversion() < "3.2.0"`. I'd have a PR for that ready, but I am not really convinced that supporting such old R versions is worth the extra lines of code ("tiny"!). Even old Ubuntu 16.04 LTS (xenial) already ships R 3.2.3 (and has soon reached EOL).

**tinytest** should probably just formally depend on R >= 3.2.0 (in the `DESCRIPTION`).

**Comment by markvanderloo** [comment]
Hi Sebastian, thank you for figuring all this out. I think that depending on `R >= 3.2.0` is acceptable, so I'll add that to 'DESCRIPTION'
