### ISSUE TITLE
A function that produces both output and error

### ISSUE THREAD

**Issue by otoomet** [markvanderloo/tinytest#80]
Consider the function:

```
root <- function(x) {
   if(x < 0) {
      cat("You cannot compute root of such numbers\n")
      print(x)
      stop("Root of negative number")
   }
   sqrt(x)
}
```

What is the best way to test the error behavior in such a function?

* If I do `tinytest::expect_error(root(-2))` the test passes but I also get output on screen.  I'd like the tests to run with no clutter.
* If I test output `tinytest::expect_output(root(-2))` I get an error
* If I wrap error in output `tinytest::expect_stdout(tinytest::expect_error(root(-2)))` I am not quite sure what I am testing, the test still passes if I remove `stop`.

While I can easily put the value inside the error message in this example, it may be more tricky with complex object with multi-line printout.  Is it considered a good habit that complete output of error message should be spit out by `stop` itself, and not complemented with ordinary printing?

Thoughts/suggestions?

**Comment by markvanderloo** [comment]
Hi Ott,


It is good practice to give a message only once. So here, I would try to give one single clean message in `stop` and avoid the use of `cat()`. Of course you are allowed to do

```r
capture.output({
  expect_error(root(-2))
})
```

to avoid output to `stdout`. The test failure will still be captured. This is better, because it makes output capturing explicit in the test file.

**Comment by markvanderloo** [comment]
Fixed it in https://github.com/markvanderloo/tinytest/commit/fda29e565d0fa5fb2904054b7c9dccb1fb351b12:

```r
> library(tinytest)
> x <- 0
> attr(x,"foo") <- "bar"
> x
[1] 0
attr(,"foo")
[1] "bar"
> tinytest::expect_equal(x,0)
----- FAILED[attr]: <-->
 call| tinytest::expect_equal(x, 0)
 diff| Attributes differ 
```

Not quite as good as I want it to be, but I'm working on better reporting (it's a challenge).
