### ISSUE TITLE
expect_warning with pattern and multiple warnings.

### ISSUE THREAD

**Issue by otoomet** [markvanderloo/tinytest#85]
I cannot find any documentation about pattern matching for `expect_warning` in case the expression issues multiple warnings.  Experimentation suggests that the test passes if any warning matches the pattern:

```r
> foo <- function() { warning("foo 1"); warning("foo 2") }
> tinytest::expect_warning(foo())
----- PASSED      : <-->
 call| tinytest::expect_warning(foo()) 
> tinytest::expect_warning(foo(), pattern="foo")
----- PASSED      : <-->
 call| tinytest::expect_warning(foo(), pattern = "foo") 
> tinytest::expect_warning(foo(), pattern="1")
----- PASSED      : <-->
 call| tinytest::expect_warning(foo(), pattern = "1") 
> tinytest::expect_warning(foo(), pattern="2")
----- PASSED      : <-->
 call| tinytest::expect_warning(foo(), pattern = "2") 
```
So both "1" and "2" are considered matching pattern.  

I think this behavior should be documented.  Maybe the user should even have an option to choose the pattern matching behavior (e.g. pattern is a vector where components are individually matched to individual warnings) although this may be a very rare need in practice.

**Comment by markvanderloo** [comment]
You're right. I'll document that before the next release.
