### ISSUE TITLE
Support for `expect_match()`

### ISSUE THREAD

**Issue by atheriel** [markvanderloo/tinytest#88]
The **testthat** package has a very convenient expectation function for when strings match a regular expression. It seems to be fairly popular in the wild, judging from [a search of all CRAN packages](https://github.com/search?q=org%3Acran+expect_match&type=code).

Obviously you can implement it yourself with

```r
expect_match <- function(x, pattern) expect_true(grepl(pattern, x))
```

but it would be nice if it was available by default, and could therefore support better error messages.

**Comment by markvanderloo** [comment]
added `expect_match()` Thanks for the suggestion! the semantics are that all strings in the first argument should match a single pattern (the second argument).

**Comment by atheriel** [comment]
Looks great, thanks!
