### ISSUE TITLE
exit_if

### ISSUE THREAD

**Issue by grantmcdermott** [markvanderloo/tinytest#89]
Hi Mark, 

I just watched your useR! talk. Very cool and it's convinced me to use `tintytest` for one of my own packages. Speaking of which...

`testthat` has a simple, but rather useful `skip_if_not_installed()` function. Really, it's just a convenience wrapper around `requireNamespace()` and `utils::packageVersion()` that's easy enough to code up oneself. But I was wondering if there's an equivalent function in `tinytest`, or appetite for introducing something along those lines?

Thanks.

**Comment by markvanderloo** [comment]
There is the `exit_file()` function, so the current workaround would be something like
```r
if (!requireNamespace("somepackage") || packageVersion("somepackage") < "1.0.0" ){
    exit_file("somepackage not installed or insufficient version (<1.0.0)")
}
```
See also `tinytest::exit_file`. 

Maybe it is better to have a more generic function like `exit_if()`, so you could do
```r
exit_if(!requireNamespace("somepackage")
exit_if(packageVersion("somepackage") < "1.0.0")
```
and `exit_if` would generate a useful message for you, like `exiting because packageVersion("somepackage") < "1.0.0" is not TRUE`

**Comment by grantmcdermott** [comment]
> Maybe it is better to have a more generic function like `exit_if()`

Yes, I think so. I don't have time to put in a PR atm but thanks for considering.

**Comment by markvanderloo** [comment]
I just added a function called `exit_if_not()`, which seems to make more sense. So now you can do (in the development version)

```r
exit_if_not(requireNamespace("roundhouse",quietly=TRUE))
```

Thanks for posting the issue. I think it triggered a nice addition to the package!

**Comment by grantmcdermott** [comment]
Excellent. Thanks Mark!
