### ISSUE TITLE
could not find function exported by the package

### ISSUE THREAD

**Issue by ccshao** [markvanderloo/tinytest#9]
tinytest works well with  `build_install_test()`, however, when I used the `check` in rstudio, it said that could not find the exported funtion.

`Error in rsplit("A_B_C_D_E", "_", 3) : could not find function "rsplit"`.

> `sessionInfo()`
> R version 3.6.0 (2019-04-26)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Linux Mint 19.1
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] tinytest_0.9.3
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1        rstudioapi_0.10   magrittr_1.5      usethis_1.5.0    
>  [5] devtools_2.0.2    pkgload_1.0.2     R6_2.4.0          rlang_0.3.4      
>  [9] tools_3.6.0       pkgbuild_1.0.3    sessioninfo_1.1.1 cli_1.1.0        
> [13] withr_2.1.2       remotes_2.0.4     assertthat_0.2.1  digest_0.6.19    
> [17] rprojroot_1.3-2   crayon_1.3.4      processx_3.3.1    callr_3.2.0      
> [21] fs_1.3.1          ps_1.3.0          curl_3.3          testthat_2.1.1   
> [25] memoise_1.1.0     glue_1.3.1        compiler_3.6.0    desc_1.2.0       
> [29] backports_1.1.4   prettyunits_1.0.2
> >

**Comment by markvanderloo** [comment]
`rsplit` is not a function in `tinytest`. Not sure what `check` in RStudio does (never used it), so I can only guess really. One thing is that it is better to run R CMD check on a tarball then on a source directory, so there may be a difference there.

**Comment by eddelbuettel** [comment]
FWIW I have been working with `tinytest` quite a bit over the last few weeks and already converted a package or two. In my testing I use mostly command-line calls but also RStudio and its handy 'check' feature.  But like Mark I do not like the opaque nature of `devtools` and generally have that tickbox off.  So it run `R CMD check ...` for me as usual also in RStudio.

Maybe you can try debug what is happening to the search path when `devtools` is used.

**Comment by ccshao** [comment]
Thanks for the quick response and sorry for the ambiguity. The `rsplit` is the function in my package that will be tested. 
Indeed I was using the `devtools::check `in Rstudio, with `tinytest 0.9.3`. 

Using `devtool::check`, Rstudio reported the error that rsplit could not be found. However,  `build_install_test()` works just fine and no complains at all. I ran the above check in a linux system.

In the afternoon I found there is a newer version of **0.9.4** and tried it out in a macox. Interestingly, both check and devtools::check work as expected. So I think the 0.9.4 fixes some bugs that might related to `devtool::check`. I like the neat output of devtools::check but will move to the pure R check in the future.

**Comment by eddelbuettel** [comment]
@markvanderloo cleaned up some code related to environments which may have been at the cause of 0.9.3 behaving differently between the two call patterns -- and as we don't run via `devtools` we did not notice.  Glad to know it is all squared now!
