### ISSUE TITLE
Add encoding argument to run_test_file (?)

### ISSUE THREAD

**Issue by vigou3** [markvanderloo/tinytest#91]
First a word to say I very much like tinytest and its simplicity. My automated grading system [Roger](https://roger-project.io/en) is in part based on the package.

Now, I have to support Windows as well as Unix (macOS, Linux) in non-English locales and file encoding issues are a real pain. The latest one I discovered:

- to avoid issues with locale management at R or RStudio startup, I follow [this solution](https://stackoverflow.com/a/54162357) and set the locale to `French_Canada.1252` in `.Renviron`;
- a test file is saved in a sane encoding (a.k.a. UTF-8);
- when running 'run_test_file`, a regex fails because accents in said regex got mangled along the way.

I think if `run_test_file` gained an `encoding` argument to would be passed to `parse`, all would be good.

Perhaps there's another way?

Thanks!

v.

**Comment by markvanderloo** [comment]
A 'locale' or encoding argument is probably a good idea. 

There are some this's and that's however: (just so I don't forget)

- CRAN tests in C locale
- can't be sure that a locale setting is available on CRAN
- locale notation is OS dependent.

**Comment by vigou3** [comment]
I would just use `parse`'s default (`encoding = "unknown"`) and pass the argument as is. Something along the lines of:
```
run_test_file <- (file, at_home = TRUE, verbose = getOption("tt.verbose", 
    2), color = getOption("tt.pr.color", TRUE), remove_side_effects = TRUE, 
    side_effects = FALSE, set_env = list(), encoding = "unknown", ...)
 {
    ...
    parsed <- parse(file = file, keep.source = TRUE, encoding = encoding)
    ...
}
```
I think this would resolve all the points you raise.

I'd be willing to propose a patch, but I'm afraid I would miss some places where test files are read.
